## Numbers, Variable & Comment

In [1]:
42

42

In [2]:
4.4

4.4

In [3]:
typeof(42)

Int64

In [4]:
typeof(4.4)

Float64

In [5]:
3 + 6 *7 

45

In [6]:
3/56

0.05357142857142857

In [7]:
grade = 34

34

In [8]:
grade

34

In [9]:
println(grade)

34


In [10]:
rank = 4

4

In [11]:
grade + rank 

38

In [12]:
typeof(rank)

Int64

In [13]:
pi

π = 3.1415926535897...

In [14]:
100 % 3

1

In [15]:
2^3

8

In [16]:
# Single line comment

In [18]:
#= 1st
2nd
3rd 
Multiline Comment
=#

## String

In [19]:
"This is Julia"

"This is Julia"

In [20]:
s1 = "This is Julia"

"This is Julia"

In [21]:
typeof(s1)

String

In [23]:
s2 = """
This is Multi Line 
Comment
"""

"This is Multi Line \nComment\n"

In [24]:
println(s2)

This is Multi Line 
Comment



In [25]:
"""It "is" raining outside """

"It \"is\" raining outside "

In [26]:
println("My grade is $grade")

My grade is 34


In [27]:
println("My grade is $(grade)")

My grade is 34


In [28]:
m1 = " I love"
m2 = "Julia"

"Julia"

In [29]:
m1 = " I love"
m2 = "Julia"; # use when dont want to print output on executing

In [30]:
string(m1,m2) #concatenation

" I loveJulia"

In [31]:
string("I" , "Love", "You")

"ILoveYou"

In [32]:
m2^100

"JuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJuliaJulia"

In [33]:
"Dev" ^ 100

"DevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDevDev"

In [34]:
m1[1]

' ': ASCII/Unicode U+0020 (category Zs: Separator, space)

In [35]:
m1[2]

'I': ASCII/Unicode U+0049 (category Lu: Letter, uppercase)

In [ ]:
m1[start index: end index]

In [37]:
m1[3:6]

" lov"

In [39]:
ch = 'm'

'm': ASCII/Unicode U+006D (category Ll: Letter, lowercase)

In [40]:
typeof(ch)

Char

In [ ]:
'md' #shows error because single quotes only store one character

## Arrays

In [43]:
[3,5,9]

3-element Vector{Int64}:
 3
 5
 9

In [44]:
[3,5,9] + [2,5,6]

3-element Vector{Int64}:
  5
 10
 15

In [48]:
arr = ["Hey", "Hi", 2 ,4.5, true]  

5-element Vector{Any}:
     "Hey"
     "Hi"
    2
    4.5
 true

In [49]:
length(arr)

5

In [50]:
typeof(arr)

Vector{Any} (alias for Array{Any, 1})

In [51]:
minimum([3,5,9])

3

In [52]:
maximum([3,5,9])

9

In [53]:
arr

5-element Vector{Any}:
     "Hey"
     "Hi"
    2
    4.5
 true

In [54]:
arr[3]

2

In [55]:
arr[2: 4]

3-element Vector{Any}:
  "Hi"
 2
 4.5

In [56]:
arr[4:4]

1-element Vector{Any}:
 4.5

In [57]:
println(arr)

Any["Hey", "Hi", 2, 4.5, true]


In [58]:
push!(arr, "34")

6-element Vector{Any}:
     "Hey"
     "Hi"
    2
    4.5
 true
     "34"

In [59]:
sort([3,5,-1])

3-element Vector{Int64}:
 -1
  3
  5

In [60]:
# with mazority of function you get to impletentation in Julia one is sort and other is sort! !-> this type of function is basically modification in original content or original object

In [61]:
sort!([3,5,-1])

3-element Vector{Int64}:
 -1
  3
  5

In [62]:
range(1, stop=100)

1:100

In [65]:
range(-10,step=5, length=10)

-10:5:35

In [66]:
range(-10, length=10)

-10:-1

In [67]:
arr1 = arr

6-element Vector{Any}:
     "Hey"
     "Hi"
    2
    4.5
 true
     "34"

In [68]:
arr1 

6-element Vector{Any}:
     "Hey"
     "Hi"
    2
    4.5
 true
     "34"

In [69]:
arr1[1] = "Bye"

"Bye"

In [70]:
arr

6-element Vector{Any}:
     "Bye"
     "Hi"
    2
    4.5
 true
     "34"

In [72]:
println(arr,arr1)

Any["Bye", "Hi", 2, 4.5, true, "34"]Any["Bye", "Hi", 2, 4.5, true, "34"]


In [73]:
# this is due to arr1 is only pointing to the arr location no new location is created

In [74]:
arr2 = copy(arr)

6-element Vector{Any}:
     "Bye"
     "Hi"
    2
    4.5
 true
     "34"

In [75]:
println(arr,arr2)

Any["Bye", "Hi", 2, 4.5, true, "34"]Any["Bye", "Hi", 2, 4.5, true, "34"]


In [76]:
arr2[1] ="Julia"

"Julia"

In [77]:
println(arr,arr2) 

Any["Bye", "Hi", 2, 4.5, true, "34"]Any["Julia", "Hi", 2, 4.5, true, "34"]


In [78]:
in(2,arr)

true

In [79]:
in(5,arr)

false

## Tuples

In [81]:
t1 = (6, 6 , true)

(6, 6, true)

In [82]:
typeof(t1)

Tuple{Int64, Int64, Bool}

In [83]:
t1[2]

6

In [84]:
t1[2] = "hello" # no modification in tuple allowed

LoadError: MethodError: no method matching setindex!(::Tuple{Int64, Int64, Bool}, ::String, ::Int64)

In [85]:
length(t1)

3

## Dictionary

In [90]:
#=
John = 555
Alice = 111
Bob = 333
=#
phonebook = Dict("John"=> "555", "Alice"=>111,"Bob"=>333)

Dict{String, Any} with 3 entries:
  "John"  => "555"
  "Alice" => 111
  "Bob"   => 333

In [91]:
keys(phonebook)

KeySet for a Dict{String, Any} with 3 entries. Keys:
  "John"
  "Alice"
  "Bob"

In [92]:
values(phonebook)

ValueIterator for a Dict{String, Any} with 3 entries. Values:
  "555"
  111
  333

In [93]:
phonebook["John"]

"555"

In [94]:
for (k, v) in phonebook
    println("$k , $v" )
end

John , 555
Alice , 111
Bob , 333


In [96]:
collect(keys(phonebook))

3-element Vector{String}:
 "John"
 "Alice"
 "Bob"

In [97]:
haskey(phonebook, "John")

true

## Sets

In [99]:
Set([1,2,3])

Set{Int64} with 3 elements:
  2
  3
  1

In [101]:
s1 = Set([1,2,3, 6 , 6]) #only store unique values

Set{Int64} with 4 elements:
  6
  2
  3
  1

In [102]:
s2 = Set([4,5, 3, 6])

Set{Int64} with 4 elements:
  5
  4
  6
  3

In [103]:
union(s1, s2)

Set{Int64} with 6 elements:
  5
  4
  6
  2
  3
  1

In [105]:
intersect(s1 , s2)

Set{Int64} with 2 elements:
  6
  3

In [106]:
issubset(s1, s2)

false

## Control Flow

### Decision Making

In [108]:
N = 34

34

In [109]:
if N > 0
    println("N is +ve")
else
    println("N is -ve")
end

N is +ve


In [110]:
N = -5 

-5

In [111]:
if N > 0
    println("N is +ve")
else
    println("N is -ve")
end

N is -ve


In [113]:
N = 14
if N > 25
    println("N is more than 25")
elseif (N>0 && N< 25)
    println("N is between 0 and 25")
else
    println("N is -ve")
end

N is between 0 and 25


### Looping

In [114]:
for i = 1:5
    println(i)
end

1
2
3
4
5


In [116]:
for i = 1:5, j =1:5
    println(i, " : " , j)
end

1 : 1
1 : 2
1 : 3
1 : 4
1 : 5
2 : 1
2 : 2
2 : 3
2 : 4
2 : 5
3 : 1
3 : 2
3 : 3
3 : 4
3 : 5
4 : 1
4 : 2
4 : 3
4 : 4
4 : 5
5 : 1
5 : 2
5 : 3
5 : 4
5 : 5


In [117]:
arr = [3, 5, "Hello"]

3-element Vector{Any}:
 3
 5
  "Hello"

In [119]:
for val in arr
    println(val)
end

3
5
Hello


In [120]:
i = 1
while i < 5
    println(i)
    i = i+1
end

1
2
3
4


## Function

In [1]:
function welcome()
    println("Welcome")
end

welcome (generic function with 1 method)

In [2]:
welcome()

Welcome


In [3]:
function welcome1(name)
    println("Hi  $name")
end

welcome1 (generic function with 1 method)

In [4]:
welcome1("Devendra")

Hi  Devendra


In [5]:
welcome2(name) = println("Hello $name")

welcome2 (generic function with 1 method)

In [6]:
welcome2("Dev")

Hello Dev


In [7]:
welcome3 = name -> println("Hello $name")

#1 (generic function with 1 method)

In [9]:
welcome3("data")

Hello data


In [10]:
function add(x,y)
    z = x + y
end

add (generic function with 1 method)

In [11]:
add(4,6)

10

In [12]:
function add(x,y)
    z = x + y
    return 
end

add (generic function with 1 method)

In [13]:
arr = [2,3,6,0,-4]

5-element Vector{Int64}:
  2
  3
  6
  0
 -4

In [14]:
sort(arr)

5-element Vector{Int64}:
 -4
  0
  2
  3
  6

In [15]:
arr

5-element Vector{Int64}:
  2
  3
  6
  0
 -4

In [16]:
sort!(arr)

5-element Vector{Int64}:
 -4
  0
  2
  3
  6

In [17]:
arr

5-element Vector{Int64}:
 -4
  0
  2
  3
  6

In [18]:
function f1(x)
    x^2
end

f1 (generic function with 1 method)

In [19]:
arr1 = [1,3,2,7,0]

5-element Vector{Int64}:
 1
 3
 2
 7
 0

In [21]:
map(f1, arr1)

5-element Vector{Int64}:
  1
  9
  4
 49
  0

## Package

In [2]:
using Pkg

In [3]:
Pkg.installed()

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Pkg.jl:566


Dict{String, VersionNumber} with 14 entries:
  "CSV"            => v"0.8.4"
  "ClassImbalance" => v"0.8.7"
  "StatsPlots"     => v"0.14.20"
  "ScikitLearn"    => v"0.6.2"
  "Lathe"          => v"0.0.9"
  "StatsBase"      => v"0.32.2"
  "IJulia"         => v"1.23.2"
  "Plots"          => v"1.13.2"
  "ROCAnalysis"    => v"0.3.2"
  "DataFrames"     => v"0.20.2"
  "Pandas"         => v"1.4.0"
  "GLM"            => v"1.4.2"
  "MLBase"         => v"0.8.0"
  "Seaborn"        => v"0.4.1"

In [24]:
Pkg.rm("CSV")

In [4]:
Pkg.installed()

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Pkg.jl:566


Dict{String, VersionNumber} with 14 entries:
  "CSV"            => v"0.8.4"
  "ClassImbalance" => v"0.8.7"
  "StatsPlots"     => v"0.14.20"
  "ScikitLearn"    => v"0.6.2"
  "Lathe"          => v"0.0.9"
  "StatsBase"      => v"0.32.2"
  "IJulia"         => v"1.23.2"
  "Plots"          => v"1.13.2"
  "ROCAnalysis"    => v"0.3.2"
  "DataFrames"     => v"0.20.2"
  "Pandas"         => v"1.4.0"
  "GLM"            => v"1.4.2"
  "MLBase"         => v"0.8.0"
  "Seaborn"        => v"0.4.1"

In [ ]:
Pkg.add("CSV")

## Vector and Matrix Preprocessing

In [5]:
using Random

In [6]:
using Pkg
Pkg.add("Random")

In [7]:
rand(3,4)

3×4 Matrix{Float64}:
 0.874668  0.660607  0.296858   0.510593
 0.70033   0.139135  0.626426   0.0334084
 0.367389  0.157146  0.0754791  0.702147

In [8]:
randn(10,2)

10×2 Matrix{Float64}:
  0.275929   0.671561
 -0.161112  -0.186606
 -0.566299   0.731822
  1.23711    1.58268
  0.858388  -0.69708
 -0.40017   -2.03558
  1.09876   -0.499928
  0.456648  -0.17046
  1.28991    0.046004
  0.655152  -1.74222

In [9]:
randstring()

"EuYGilrc"

In [10]:
randstring('A':'B', 50)

"ABAABBBBBABABAABAABBBBABAABABAABABBBAAAAABBBBBBBAA"

In [12]:
v1 = Vector(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [13]:
reshape(v1, (2,5))

2×5 Matrix{Int64}:
 1  3  5  7   9
 2  4  6  8  10

## Algebra Operations

In [15]:
ones(3, 5)

3×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [16]:
zeros(2, 5 , 6)

2×5×6 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 5] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 6] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [17]:
using LinearAlgebra

In [18]:
I(4)

4×4 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅
 ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  1

In [19]:
I(10)

10×10 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1

In [23]:
M = [2 4 5; 1 2 3; 6 7 0]

3×3 Matrix{Int64}:
 2  4  5
 1  2  3
 6  7  0

In [24]:
typeof(M)

Matrix{Int64} (alias for Array{Int64, 2})

In [25]:
size(M)

(3, 3)

In [26]:
M[1,: ]

3-element Vector{Int64}:
 2
 4
 5

In [27]:
M[:,2]

3-element Vector{Int64}:
 4
 2
 7

In [28]:
N = [1 2 3 ; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [29]:
[M N] #concatenate horizontally

3×6 Matrix{Int64}:
 2  4  5  1  2  3
 1  2  3  4  5  6
 6  7  0  7  8  9

In [30]:
[M;N] #concatenate vertically

6×3 Matrix{Int64}:
 2  4  5
 1  2  3
 6  7  0
 1  2  3
 4  5  6
 7  8  9

In [31]:
hcat(M, N)

3×6 Matrix{Int64}:
 2  4  5  1  2  3
 1  2  3  4  5  6
 6  7  0  7  8  9

In [32]:
vcat(M, N)

6×3 Matrix{Int64}:
 2  4  5
 1  2  3
 6  7  0
 1  2  3
 4  5  6
 7  8  9

In [33]:
transpose(M)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 2  1  6
 4  2  7
 5  3  0

In [34]:
tr(M) #trash of M

4

In [35]:
det(M) #determinant

5.000000000000001

In [36]:
inv(M) #inverse

3×3 Matrix{Float64}:
 -4.2   7.0   0.4
  3.6  -6.0  -0.2
 -1.0   2.0   0.0

In [37]:
UpperTriangular(M)

3×3 UpperTriangular{Int64, Matrix{Int64}}:
 2  4  5
 ⋅  2  3
 ⋅  ⋅  0

In [38]:
LowerTriangular(M)

3×3 LowerTriangular{Int64, Matrix{Int64}}:
 2  ⋅  ⋅
 1  2  ⋅
 6  7  0

In [39]:
eigvecs(M)

3×3 Matrix{Float64}:
 -0.424033  -0.742562  -0.645135
 -0.292089   0.639301  -0.358268
  0.857251  -0.19974   -0.674866

In [40]:
eigvals(M)

3-element Vector{Float64}:
 -5.352954259951673
 -0.09882411688237432
  9.451778376834048